version: "0.2"
ignorePaths:
  [
    "./customWords.txt",
    "./.github/**/*.yml",
    "./secrets.baseline",
    "./*.env",
    "./*.lock",
    "./*.toml",
    "./.gitignore",
    "./.gitattributes",
  ]
dictionaryDefinitions:
  [{ name: customWords, path: "./.customWords.txt", addWords: true }]
dictionaries:
  - en_US
  - "!en_GB"
  - companies
  - softwareTerms
  - node
  - typescript
  - python
  - html
  - css
  - filetypes
  - customWords
words: []
ignoreWords: []
import: []
caseSensitive: true
languageSettings:
  - languageId: python
