name: Auto Update Pre-commit Hooks

on:
  schedule:
    - cron: "5 0 1 * *"

jobs:
  auto-update:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'ksquarekumar/pdm-python' }}
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v5.2.0
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/pre-commit-autoupdate
          title: Auto-update pre-commit hooks
          commit-message: "Chore(deps): Auto-update pre-commit hooks"
          body: |
            Update versions of tools in pre-commit
            configs to latest version
          labels: dependencies
